version: "3.8"

services:
  mongodb:
    image: mongo:6.0.4
    container_name: todo-mongo
    restart: no
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - 27017:7017
    volumes:
      - db:/data/db
  app:
    links:
      - mongodb
    build: ./backend
    container_name: todo-node
    restart: no
    env_file: ./.env
    ports:
      - 3000:2000
    volumes:
      - type: bind
        source: .
        target: /backend
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    stdin_open: true
    tty: true
volumes:
  db: